### PR TITLE
Fix bug of detecting empty tag

### PR DESCRIPTION
**Pull request by trunone**
Skipping space inside empty tag, like `<params />`.
Add ending character of tag string.

### CODE REVIEW

**Comment by sgieseking** [comment]
This would seem to also allow any spaces in the tag name <par ams/>, <p  arams/>.  I'm not sure that is valid for xml tags.

Probably should just move the tag[tagLength] = 0 to after the while loop so it is in one place.  It's not needed for the string compare strncmp() but is needed for the log_debug().

**Comment by trunone** [comment]
Oh, sorry, I didn't consider those situations. I just quickly fixed for xml-rpc.net, cause it sends `<params />`. Maybe you have better solution to prevent those invalid tags.

**Comment by sgieseking** [comment]
If you are controlling the client using XmlRpc.net, then setting the UseEmptyElementTag to false is a current solution.  I'll think about a better solution that maintains the parameter integrity.

**Comment by trunone** [comment]
I had tried that. But I still got parse error return. I didn't trace the bug.

**Comment by sgieseking** [comment]
It would help if you can run the AnyRPC server with the log4cplus.properties file set to show all of the AnyRPC.Connection log data.  So just comment out that line:

    #log4cplus.logger.AnyRPC.Connection      = WARN

If you want the log output to go directly to a file, then you can change the first line:

    log4cplus.rootLogger                    = TRACE, FILE

It will then log the exact xmlrpc request that is being made in the ExecuteRequest method.  So included in the log data will be something like the following:

    06/23/16 20:06:03.585.955 [79552] DEBUG AnyRPC.Connection     419:virtual bool anyrpc::HttpConnection::ExecuteReques - ContentLength=198, request=<?xml version="1.0" encoding="utf-8" ?><methodCall><methodName>multiply</methodName><params><param><value><i4>10</i4></value></param><param><value><i4>12</i4></value></param></params></methodCall>

We can then look at what XmlRpc.net is generating for the request.

**Comment by sgieseking** [comment]
Try the new code.  It handles the whitespace inside the tag.

**Comment by JanPlitzkow** [comment]
The new version gives compiler errors if using VisualStudio 2015. For line 51 in file "reader.h"
`virtual bool IsWhiteSpace(char c) { return std::isspace(c); }`
I get the error

> "std::isspace": keine übereinstimmende überladene Funktion gefunden

which means that no fitting function could be found. It only proposes a function based on this template:
```
template<class _Elem> inline
	bool (isspace)(_Elem _Ch, const locale& _Loc)
	{	// test if character is whitespace, locale specific
	return (_USE(_Loc, ctype<_Elem>).is(ctype_base::space, _Ch));
	}
```
But for this the local specifier is missing.

**Comment by sgieseking** [comment]
Just needed to move the include for <cctype> and fix the compare so VS doesn't generate a warning.

**Pull request closed without merging**
