### PR TITLE
Enable setting number of threads for TCP thread pool servers.

### PR DESCRIPTION
**Pull request by JanPlitzkow**
You might want to create a TCP-TP-server of a specific subtype while specifying the number of used threads.
e.g.:
const unsigned numThreads = 10;
Server *server = 0;
server = new JsonTcpServer(numThreads);

This was not possible without these changes.

### CODE REVIEW

**Comment by JanPlitzkow** [comment]
I just saw, that the Http-server might need the same changes...

**Comment by sgieseking** [comment]
A brief look seemed reasonable, but give me a day or two to fully review.

**Comment by JanPlitzkow** [comment]
No problem. 
Please review both my commits as one, because the first commit on its own is not correct and incomplete.

**Comment by sgieseking** [comment]
I checked in a set of changes similar to your pull request but credited to you.  I had to make some modifications.  The xxxHttpServerTP constructors need the AddHandler call.  I also added a no parameter xxxTcpServerTP call so you are not required to provide the numThreads parameter and it will use the default.

**Comment by JanPlitzkow** [comment]
Looks fine to me. 
- With the HttpServer you are right... Sorry for that.
- For the TcpServerTP the default no-parameter-constructor would just be the same, wouldn't it? I think it would not be neccessary to explicitly define a no-parameter-constructor, but it doesn't hurt either ;)

**Pull request closed without merging**
