### PR TITLE
For Cygwin support

### PR DESCRIPTION
**Pull request by trunone**

### CODE REVIEW

**Comment by sgieseking** [comment]
Thanks for providing the update.  I'd like to test it on my computer before performing the merge.  I don't have cygwin setup on my current development computer so it might take a couple of days for me to get to this.

**Comment by sgieseking** [comment]
With the socket definitions for the tcp keepalive, do you know if these actually work under cygwin?  My understanding with mingw is that they don't work, potentially because the winsock implementation uses a different call.  The capability is currently not used by anyrpc so in that respect, it doesn't really matter.  I just don't like making it appear to work if it doesn't.

**Comment by trunone** [comment]
I haven't tested that tcp keepalive is working or not.
But from this stackoverflow answer [link](http://stackoverflow.com/a/6801441).
I think it will work.

**Comment by sgieseking** [comment]
Looking through the cygwin source, I don't see that will properly respond to these options. 
netinet/tcp.h defines the following as IPPROTO_TCP options.

    /*
     * User-settable options (used with setsockopt).
     */
    #ifndef TCP_NODELAY
    #define TCP_NODELAY     0x01    /* don't delay send to coalesce packets */
    #define TCP_MAXSEG      0x02    /* set maximum segment size */
    #endif
    #define TCP_NOPUSH      0x04    /* don't push last block of write */
    #define TCP_NOOPT       0x08    /* don't use TCP options */

So TCP_NOPUSH would conflict with TCP_KEEPIDLE but I don't see that TCP_NOPUSH is used in cygwin.  I also don't see any processing related to the keep alive options.  I think you can enable keep alive messages but not net the keep alive interval information.

**Pull request closed without merging**
