### PR TITLE
Bug fixing and HTTP access control (CORS) support

### PR DESCRIPTION
**Pull request by AlbrechtL**
See commit description for details.

### CODE REVIEW

**Comment by AlbrechtL** [comment]
Added Fixed some bugs that crashed anyrpc

**Comment by sgieseking** [comment]
A few questions/comments regarding the changes:
1.	You probably saw that I already fixed the MessagePackReader::ParseUint8 issues from your commits.  I also added a test case to first show that there was a problem and then verify that it was fixed.

2.	What is the need to export MessagePackRpcHandler from the DLL.  I considered it an internal function and not necessary to export.  How are you trying to use the function directly from the DLL?

3.	With the two crashes that you mention.  Can you describe the situation that they occurred?  Is this with the standard handlers?  Can you provided a simple example that makes this occur so that it can be added to the test set?
a.	In the case of Client::ReadResponse, response_ and contentAvail_ should both be valid at that point.  If they are not, then the socket_.Receive call is not really valid.
b.	In the case of Client::ProcessResponse, requestId_ should have a valid entry.  If it doesn’t, then the requestId_.front() call has undefined behavior.

4.	With the HTTP access control support, in what context are you needing this?

**Comment by AlbrechtL** [comment]
to 1. Yes, I have seen it. Thanks for fixing!
to 2. No, I don't call this function directly but the linker complained "Unresolved symbol ..." when I was trying to bind anyrpc to my program. In order to fix this I simply added this function to the DLL and the anyrpc was working.
to 3. Sorry, I don't have a test program for the two crashes because I don't know exactly why this happens. The situation was the following. Program A (MS Windows) and program B (Linux) are communicating via TCP MessagePack (both are using anyrpc) with each other. Program A is unstable and crashes unpredictably (the problem is NOT anyrpc). But sometimes if program A crashes also program B crashed and the debugger told me these two problems in anyrpc. After I added the "if" conditions program B was stable and independent from the program A crashes.
to 4.  Program C is a HTML5 web app which runs in a browser, Google Chrome for example. I'm using [jsonrpcjs](https://github.com/gimmi/jsonrpcjs) to connect to program B (see 3.). For security reasons modern web browsers don't allow to connect to a sever with a different domain or port where is web app is hosted. Because anyrpc have to use a different port CORS is necessary to connect to it.

**Comment by sgieseking** [comment]
Regarding 2. Maybe the problem is that you need to define ANYRPC_DLL in your Windows program.  I was able to reproduce the behavior that you indicated.  Windows is a bit funny in the use of dllexport/dllimport.  I would eliminate the xxxRpcHandler function declarations from the header but they are used by both the protocol specific server and the AnyHttpServer.  I may see if there is a better way to write this or just add the exports to the xxxRpcHandler calls as indicated.

Regarding 3. I will try to reproduce the crash that you describe.  My concern is that there is a different/deeper problem that needs to be addressed, possibly with the selections in Socket::FatalError().

Regarding 4. I don't really work with web apps so thanks for providing the code.  I will include that as part of resolving the other issues.

**Comment by sgieseking** [comment]
Regarding 3.  Since you indicate that the crash that the change fixed was on the Linux side, did you try building with BUILD_WITH_ADDRESS_SANITIZE?  This helps to detect memory corruption issues in case that is the issue with response_ being 0.  You can also use the logging with some of the entries set to log more data such as AnyRpc.Socket and AnyRpc.Client.  I used both of these extensively during the development.

**Comment by sgieseking** [comment]
I have added the CORS code and the requestId_ list check in the ProcessResponse function with some additional related modifications.  Since I wasn't pulling the code directly, I included a reference to you in the comments.
I'm still evaluating the change to ReadResponse but haven't been able to reproduce the problem.  As previously mentioned, it seems like something else may be going on that this fix is really just covering up.

**Comment by AlbrechtL** [comment]
Thanks for all the investigations and the CORS code transfer!
Regarding 2. I will try that! 
Regarding 3. The next time I build the application with BUILD_WITH_ADDRESS_SANITIZE and the log features and then we can see much better whats going on.

For now the bugs are documented and I close this pull request.

**Pull request closed without merging**
